import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from './components/layout/Footer/Footer'
import Navbar from "./components/layout/Navbar/Navbar";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "900"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} `}>
        <Navbar />
        <div className=''>
        {children}
        </div>
      <Footer />
      </body>
    </html>
  );
}
