import "./global.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import QueryProvider from "./providers/QueryProvider";
import ReduxProvider from "./providers/ReduxProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toast } from "@/components/ui/toast";
import Session from "./providers/Session";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "900"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} `}>
        <Session>
          <QueryProvider>
            <ReduxProvider>
            <div className="">{children}</div>
            </ReduxProvider>
          </QueryProvider>
        </Session>
      </body>
    </html>
  );
}
